import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'ru' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  ru: {
    platform: 'Платформа',
    search: 'Поиск...',
    profile: 'Профиль',
    login: 'Войти',
    register: 'Зарегистрироваться',
    loginLabel: 'Логин',
    loginPlaceholder: 'Введите логин',
    passwordLabel: 'Пароль',
    passwordPlaceholder: 'Введите пароль',
    forgotPassword: 'Забыли пароль?',
    cancel: 'Отмена',
    loginButton: 'Войти',
    emailLabel: 'Email',
    emailPlaceholder: 'Введите email',
    confirmPasswordLabel: 'Подтверждение пароля',
    confirmPasswordPlaceholder: 'Повторите пароль',
    agreeToTerms: 'Я согласен с условиями использования и политикой конфиденциальности',
    registerButton: 'Зарегистрироваться',
    passwordMismatch: 'Пароли не совпадают',
    menu: 'Меню',
    myCompany: 'Моя компания',
    myProjects: 'Мои проекты',
    myStartups: 'Мои стартапы',
    news: 'Новости',
    knowledgeBase: 'База знаний',
    education: 'Обучение',
    partnershipProgram: 'Партнерская программа',
    settings: 'Настройки',
    licenseAndPayment: 'Лицензия и оплата',
    support: 'Поддержка',
    platformNews: 'Новости платформы',
    colorScheme: 'Цветовая схема',
    blue: 'Синий',
    purple: 'Фиолетовый',
    green: 'Зеленый',
    orange: 'Оранжевый',
    online: 'В сети',
    typeMessage: 'Введите сообщение...',
    aboutUs: 'О нас',
    help: 'Помощь',
    privacy: 'Конфиденциальность',
    allSystemsOperational: 'Все системы работают',
    platformUpdate: 'Обновление платформы v2.0',
    platformUpdateDesc: 'Мы рады представить новую версию платформы с улучшенным интерфейсом и расширенными возможностями.',
    newTeamMembers: 'Новые участники команды',
    newTeamMembersDesc: 'В нашу команду присоединилось 5 новых специалистов для улучшения качества обслуживания.',
    webinarSchedule: 'Расписание вебинаров',
    webinarScheduleDesc: 'Опубликовано расписание вебинаров на первый квартал 2026 года.',
    gettingStarted: 'Начало работы',
    userGuides: 'Руководства пользователя',
    faq: 'FAQ',
    technicalDocs: 'Техническая документация',
    videoTutorials: 'Видеоуроки',
    tipsAndTricks: 'Советы и хитрости',
    articles: 'статей',
    platformBasics: 'Основы работы с платформой',
    advancedFeatures: 'Продвинутые возможности',
    systemAdministration: 'Администрирование системы',
    hours: 'часа',
    beginner: 'Начальный',
    intermediate: 'Средний',
    advanced: 'Продвинутый',
    becomePartner: 'Станьте нашим партнером',
    becomePartnerDesc: 'Получайте до 30% от каждого привлеченного клиента',
    join: 'Присоединиться',
    highCommissions: 'Высокие комиссии',
    highCommissionsDesc: 'До 30% с каждой продажи',
    support247: 'Поддержка 24/7',
    support247Desc: 'Персональный менеджер',
    revenueGrowth: 'Рост дохода',
    revenueGrowthDesc: 'Регулярные выплаты',
    darkMode: 'Темная тема',
    lightMode: 'Светлая тема',
    language: 'Язык',
    sortBy: 'Сортировка',
    filterByTopic: 'Фильтр по темам',
    viewMode: 'Вид',
    newest: 'Новые',
    oldest: 'Старые',
    popular: 'Популярные',
    allTopics: 'Все темы',
    updates: 'Обновления',
    announcements: 'Объявления',
    events: 'События',
    listView: 'Список',
    gridView: 'Сетка',
    compactView: 'Компактный',
    messenger: 'Мессенджер',
    contacts: 'Контакты',
    offline: 'Не в сети',
    businessNotifications: 'Бизнес-уведомления',
    aiAssistant: 'ИИ помощник',
    aiAssistantDescription: 'Задайте вопрос или выберите готовый сценарий',
    aiSuggest1: 'Как создать новый проект?',
    aiSuggest2: 'Показать аналитику за месяц',
    aiSuggest3: 'Помощь с настройками',
    aiInputPlaceholder: 'Задайте вопрос...',
    ask: 'Спросить',
    contactAnna: 'Анна Иванова',
    contactPeter: 'Петр Сидоров',
    contactMaria: 'Мария Петрова',
    contactIvan: 'Иван Иванов',
    chatMessage1: 'Привет! Как дела?',
    chatMessage2: 'Отлично, спасибо!',
    notifTitle1: 'Новый проект',
    notifMessage1: 'Добавлен проект "Веб-платформа"',
    notifTime1: '5 мин назад',
    notifTitle2: 'Обновление',
    notifMessage2: 'Система обновлена до версии 2.0',
    notifTime2: '1 час назад',
    notifTitle3: 'Встреча',
    notifMessage3: 'Напоминание о встрече в 15:00',
    notifTime3: '2 часа назад',
    companyInfo: 'Информация о компании',
    companyManagement: 'Управление информацией о вашей компании',
    companyName: 'Название компании',
    companyNameValue: 'ООО "Технологии будущего"',
    inn: 'ИНН',
    innValue: '7701234567',
    employees: 'Сотрудников',
    employeesValue: '24 человека',
    registrationDate: 'Дата регистрации',
    registrationDateValue: '15 марта 2020',
    yourActiveProjects: 'Ваши активные проекты',
    projectAlpha: 'Проект Alpha',
    projectBeta: 'Проект Beta',
    projectGamma: 'Проект Gamma',
    inProgress: 'В процессе',
    planning: 'Планирование',
    completed: 'завершено',
    chatPanel: 'Панель чата',
    swapPosition: 'Поменять местами',
    collapse: 'Свернуть',
    expand: 'Развернуть',
  },
  en: {
    platform: 'Platform',
    search: 'Search...',
    profile: 'Profile',
    login: 'Login',
    register: 'Register',
    loginLabel: 'Login',
    loginPlaceholder: 'Enter login',
    passwordLabel: 'Password',
    passwordPlaceholder: 'Enter password',
    forgotPassword: 'Forgot password?',
    cancel: 'Cancel',
    loginButton: 'Login',
    emailLabel: 'Email',
    emailPlaceholder: 'Enter email',
    confirmPasswordLabel: 'Confirm Password',
    confirmPasswordPlaceholder: 'Repeat password',
    agreeToTerms: 'I agree to the terms of use and privacy policy',
    registerButton: 'Register',
    passwordMismatch: 'Passwords do not match',
    menu: 'Menu',
    myCompany: 'My Company',
    myProjects: 'My Projects',
    myStartups: 'My Startups',
    news: 'News',
    knowledgeBase: 'Knowledge Base',
    education: 'Education',
    partnershipProgram: 'Partnership Program',
    settings: 'Settings',
    licenseAndPayment: 'License & Payment',
    support: 'Support',
    platformNews: 'Platform News',
    colorScheme: 'Color Scheme',
    blue: 'Blue',
    purple: 'Purple',
    green: 'Green',
    orange: 'Orange',
    online: 'Online',
    typeMessage: 'Type a message...',
    aboutUs: 'About Us',
    help: 'Help',
    privacy: 'Privacy',
    allSystemsOperational: 'All systems operational',
    platformUpdate: 'Platform Update v2.0',
    platformUpdateDesc: 'We are excited to introduce a new version of the platform with improved interface and enhanced features.',
    newTeamMembers: 'New Team Members',
    newTeamMembersDesc: '5 new specialists have joined our team to improve service quality.',
    webinarSchedule: 'Webinar Schedule',
    webinarScheduleDesc: 'Webinar schedule for the first quarter of 2026 has been published.',
    gettingStarted: 'Getting Started',
    userGuides: 'User Guides',
    faq: 'FAQ',
    technicalDocs: 'Technical Documentation',
    videoTutorials: 'Video Tutorials',
    tipsAndTricks: 'Tips & Tricks',
    articles: 'articles',
    platformBasics: 'Platform Basics',
    advancedFeatures: 'Advanced Features',
    systemAdministration: 'System Administration',
    hours: 'hours',
    beginner: 'Beginner',
    intermediate: 'Intermediate',
    advanced: 'Advanced',
    becomePartner: 'Become Our Partner',
    becomePartnerDesc: 'Earn up to 30% from each client you refer',
    join: 'Join',
    highCommissions: 'High Commissions',
    highCommissionsDesc: 'Up to 30% per sale',
    support247: '24/7 Support',
    support247Desc: 'Personal manager',
    revenueGrowth: 'Revenue Growth',
    revenueGrowthDesc: 'Regular payments',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    language: 'Language',
    sortBy: 'Sort By',
    filterByTopic: 'Filter by Topic',
    viewMode: 'View',
    newest: 'Newest',
    oldest: 'Oldest',
    popular: 'Popular',
    allTopics: 'All Topics',
    updates: 'Updates',
    announcements: 'Announcements',
    events: 'Events',
    listView: 'List',
    gridView: 'Grid',
    compactView: 'Compact',
    messenger: 'Messenger',
    contacts: 'Contacts',
    offline: 'Offline',
    businessNotifications: 'Business Notifications',
    aiAssistant: 'AI Assistant',
    aiAssistantDescription: 'Ask a question or select a ready-made scenario',
    aiSuggest1: 'How to create a new project?',
    aiSuggest2: 'Show analytics for the month',
    aiSuggest3: 'Help with settings',
    aiInputPlaceholder: 'Ask a question...',
    ask: 'Ask',
    contactAnna: 'Anna Ivanova',
    contactPeter: 'Peter Sidorov',
    contactMaria: 'Maria Petrova',
    contactIvan: 'Ivan Ivanov',
    chatMessage1: 'Hi! How are you?',
    chatMessage2: 'Great, thanks!',
    notifTitle1: 'New Project',
    notifMessage1: 'Project "Web Platform" has been added',
    notifTime1: '5 min ago',
    notifTitle2: 'Update',
    notifMessage2: 'System updated to version 2.0',
    notifTime2: '1 hour ago',
    notifTitle3: 'Meeting',
    notifMessage3: 'Reminder about meeting at 3:00 PM',
    notifTime3: '2 hours ago',
    companyInfo: 'Company Information',
    companyManagement: 'Manage your company information',
    companyName: 'Company Name',
    companyNameValue: 'LLC "Future Technologies"',
    inn: 'INN',
    innValue: '7701234567',
    employees: 'Employees',
    employeesValue: '24 people',
    registrationDate: 'Registration Date',
    registrationDateValue: 'March 15, 2020',
    yourActiveProjects: 'Your Active Projects',
    projectAlpha: 'Project Alpha',
    projectBeta: 'Project Beta',
    projectGamma: 'Project Gamma',
    inProgress: 'In Progress',
    planning: 'Planning',
    completed: 'completed',
    chatPanel: 'Chat Panel',
    swapPosition: 'Swap Position',
    collapse: 'Collapse',
    expand: 'Expand',
  },
};

// Default fallback value
const defaultContextValue: LanguageContextType = {
  language: 'ru',
  setLanguage: () => {},
  t: (key: string) => key,
};

const LanguageContext = createContext<LanguageContextType>(defaultContextValue);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('ru');

  const t = (key: string): string => {
    const translation = translations[language]?.[key as keyof typeof translations.ru];
    return translation || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}